### ISSUE TITLE
Create processor class for stopwords/stemming

### ISSUE THREAD

**Issue by robertcepa** [smaske96/twitter_sentiment_analysis#1]
Takes corpus, stopwords, stemmer and treshhold in constructor, does treshold preprocessing.
Keeping words in memory is OK, english dictionary has like 15 mbs max.

**Comment by robertcepa** [comment]
I'll make it use Tweet() instead of corpus, do we ignore hashtags, mentions, urls for now?

**Comment by smaske96** [comment]
Yeah, let's just use text for now.
